---
- name: Install Apache
  hosts: all
  sudo: yes
  tasks:
    - name: install apache
      apt: name=apache update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service: name=apache state=restarted