---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "Show Network Interfaces"
      command: hostname -I
      register: details
    - name: 'Get Interfaces details'
      debug:
        msg: "{{ details.stdout }}"