---
- hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: "Show Network Interfaces"
      command: date
      register: details
    - name: 'Get Interfaces details'
      debug:
        msg: "{{ details.stdout }}"