- name: Vitals
  hosts: webservers
  vars:
    csvPath: /root/ansible/ansible-project/AnsibleFiles/
    csvFileName: vitals.csv
    headers: IpAddress, Uptime, CPU_Usage, Memory_Usage

  tasks:
  - name: Get IP Address
    shell: "hostname -I"
    register: ipAddress
  - name: Get uptime
    shell: uptime -p
    register: uptime
  - name: Get CPU_Usage
    shell: "top -bn1 | grep 'Cpu(s)' | sed 's/.*, *\\([0-9.]*\\)%* id.*/\\1/'"
    register: CPU_Usage
  - name: Get Memory_Usage
    shell: "free -m | awk 'NR==2{printf \"%.2f%%\", $3*100/$2 }'"
    register: Memory_Usage
  - name: Save CSV headers
    ansible.builtin.lineinfile:
      dest: "{{ csvPath }}/{{ csvFileName }}"
      line: "{{ headers }}"
      create: true
      state: present
    delegate_to: localhost
    run_once: true

  - name: Build out CSV file
    ansible.builtin.lineinfile:
      dest: "{{ csvPath }}/{{ csvFileName }}"
      line: "{{ ipAddress.stdout }},{{ uptime.stdout }},{{ CPU_Usage.stdout }},{{ Memory_Usage.stdout }}"
      create: true
      state: present
    delegate_to: localhost
  - name: Read in CSV to variable
    community.general.read_csv:
      path: "{{ csvPath }}/{{ csvFileName }}"
    register: csv_file
    delegate_to: localhost
    run_once: true
 