- name: Vitals
  hosts: localhost
  tasks:
    - name: Get uptime of localhost
      shell: uptime -p
      register: uptime
    - name: Reporting
      copy:
        content: "{{ inventory_hostname }},{{ uptime.stdout }}"
        dest: "/root/ansible/ansible-project/AnsibleFiles/uptime.csv"
    - name: Disk Space
      shell: "df -h / | awk 'NR==2{print $5}'"
      register: diskSpace
      copy:
        content: "{{ inventory_hostname }},{{ diskSpace.stdout }}"
        dest: "/root/ansible/ansible-project/AnsibleFiles/uptime.csv"